[package]
name = "infuse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
darling = "0.14.1"
infuse-macros = { version = "0.1.0", path = "../infuse-macros" }
